# 0. Imports

In [1]:
import numpy as np
import torch
import torch.nn as nn
from torch_geometric.utils.convert import from_networkx


In [2]:
from graph_analysis.get_graphs import lastfm_graph, deezer_graph

# Node : person. Edge : follow relationship. Features : likes.
print(deezer_graph) # Target : gender
print(lastfm_graph) # Target : country

Graph with 28281 nodes and 92752 edges
Graph with 7624 nodes and 27806 edges


# 1. Embedding

In [3]:
print(deezer_graph.nodes[0]["feat"])

tensor([[-0.8529, -0.9701,  0.6632,  ..., -0.6114, -0.1813, -0.5893],
        [ 0.6530, -0.2802,  1.3212,  ..., -1.7342,  1.8870, -2.2688],
        [-1.1312,  0.5407, -1.6709,  ...,  0.1466, -0.3819,  1.5631],
        ...,
        [-1.0725,  0.2571,  1.1380,  ...,  0.2480, -0.3074,  1.3957],
        [-1.0725,  0.2571,  1.1380,  ...,  0.2480, -0.3074,  1.3957],
        [-1.0725,  0.2571,  1.1380,  ...,  0.2480, -0.3074,  1.3957]])


# 1. GNN

In [3]:
# Convert the graph into PyTorch geometric
pyg_graph = from_networkx(deezer_graph)

print("Graph:", pyg_graph)
print("Features:", pyg_graph.feat[:5])
print("Target:", pyg_graph.target[:5])
print("Edge index:", pyg_graph.edge_index)

KeyboardInterrupt: 

In [ ]:
# Split the data 
train_ratio = 0.2
num_nodes = pyg_graph.feat.shape[0]
num_train = int(num_nodes * train_ratio)
idx = [i for i in range(num_nodes)]

np.random.shuffle(idx)
train_mask = torch.full_like(pyg_graph.target, False, dtype=bool)
train_mask[idx[:num_train]] = True
test_mask = torch.full_like(pyg_graph.target, False, dtype=bool)
test_mask[idx[num_train:]] = True

print(train_mask)
# tensor([ True, False, False, False, False])
print(test_mask)
# tensor([False,  True,  True,  True,  True])

AttributeError: 'list' object has no attribute 'shape'